main.c
void function1()
Referenced by main.
void function2()
Referenced by main.
void function3()
Referenced by main.
void function4(int value1, int value2)
Referenced by main.
void function5(int value1, int value2, int(*opp)(int, int))
Referenced by main.
int add(int num1, int num2)
Referenced by main.
int sub(int num1, int num2)
Referenced by main.
int main()
References add, function1, function2, function3, function4, function5, sub.